name: 03 - Actions

on: 
    push:
        branches: "feature/**"

jobs:
    checkout_DotNet_docker:
        runs-on: ubuntu-latest
        steps:            
            - name: Git Checkout
              uses: actions/checkout@v2
            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                dotnet-version: '8.0.x'
            - name: Restore dependencies
              run: dotnet restore
            - name: Build
              run: dotnet build --no-restore
            - name: cd test
              run: cd br.com.fiap.alert.teste/
            - name: Test
              run: dotnet test --no-build --verbosity normal
            - name: cd back
              run: cd ..  
            - name: cd run
              run: cd br.com.fiap.alert.api/
            - name: run 
              run: dotnet run