# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fiap-webservice-dev

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9f83f10d76594fc4aaeb50f412bea1af }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2ea81b9def054336afdb5c1b457f1557 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9f83f10d76594fc4aaeb50f412bea1af }}/victorfqueiroz/webservice-com-asp-net:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fiap-webservice-dev'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8bfe958263e4461e8d7c019247b8304b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9f83f10d76594fc4aaeb50f412bea1af }}/victorfqueiroz/webservice-com-asp-net:${{ github.sha }}'