name: CI/CD Pipeline

on:
  push:
    branches: 
      - master
      - "feature/**"
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release
      
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
      
    - name: Run API
      run: |
        cd br.com.fiap.alert.api
        dotnet run &
        sleep 10
